spring:
  dubbo:
    appname: xxl-job-consumer
    registry: zookeeper://47.75.95.136:80
    protocol: dubbo
    port: 20801

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
      #addresses: http://localhost:8080/xxl-job-admin

    ### xxl-job executor address
    executor:
      appname: xxl-job-executor
      ip:
      port: 8888
      ### xxl-job log path
      logpath: /data/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: -1

    ### xxl-job, access token
    accessToken: 123
