server:
  # 应用端口
  port: 8071
  # tomcat 配置
  tomcat:
    max-threads: 500 # 最大线程数量 默认200
    uri-encoding: UTF-8
    max-connections: 1000 # 最大连接数量 1000
    min-spare-threads: 50 # 初始化线程是20
  servlet:
    context-path: /user

management:
  endpoints.:
    shutdown:
      enabled: true
      sensitive: false

# javamelody
javamelody:
  init-parameters:
    storage-directory: user

# 激活配置文件
spring:
  profiles:
    active: dev

