spring:
  # 表示放在classpath的i18n文件夹，文件前缀为mess
#  messages:
#    basename: language/messages
  datasource:
    # driverClassName: net.sf.log4jdbc.DriverSpy
    # url: jdbc:log4jdbc:mysql://mysql.zhangzp.cn:3306/hadoop2
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.241:3306/estate?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull
    username: admin
    password: bckj2018
    filters: stat
    maxActive: 30
    initialSize: 5
    maxWait: 60000
    minIdle: 5
    maxIdle: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 1200000
    validationQuery: select 2
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  # Spring boot http编码配置(CharacterEncodingFilter)
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  ###文件上传限制
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  ###redis配置
  redis:
    host: 192.168.1.221
    port: 46379
    password: 123456
    database: 0
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最大空闲连接
        min-idle: 1
        # 连接池最大阻塞等待时间
        max-wait: -1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #
    publisher-confirms: true
  dubbo:
    appname: template-service-provider
    server: true
    registry: zookeeper://192.168.1.161:2181
    monitor:
    protocol: dubbo
    port: -1
    threads: 500
    version: 1.0.0
